### ISSUE TITLE
Add support for Spring REST annotations

### ISSUE THREAD

**Issue by breun** [openapi-tools/swagger-maven-plugin#10]
The plugin that this plugin is based on (https://github.com/kongchen/swagger-maven-plugin) supports both JAX-RS and Spring annotations. It seems this plugin currently only supports JAX-RS. Are there any plans to add support for Spring annotations (`@RestController`, `@RequestMapping`, `@GetMapping`, `@PostMapping`, etc.) to this plugin? Or do you know of another project that supports Spring annotations and OpenAPI v3?

**Comment by langecode** [comment]
There are no plans to add support for Spring in this plugin. The plugin was specifically designed to only be a small wrapper around the functionality already present in Swagger. Where the plugin you reference re-implement much of the functionality needed to parse JAX-RS annotations and populate the OpenAPI model. Thus ensuring the same result from build time generation as when using the Swagger servlet based runtime generation (for instance supporting the `ReaderListener` from Swagger core framework). Furthermore as it is a thin wrapper there is much less maintenance, e.g., upgrading from OpenAPI v2 to OpenAPI v3.

I am not sure whether the Swagger core framework has support for Spring REST annonations if that is so I guess it should be possible to also include Spring support with this plugin. Feel free to do propose a pull-request if interested.
