### ISSUE TITLE
Add pretty-print option to JSON generation

### ISSUE THREAD

**Issue by cjelger** [openapi-tools/swagger-maven-plugin#11]
It would be nice to have an option to generate a "pretty-printed" JSON schema. The current JSON schema is nicely compact but it's unreadable by humans.

It should be straightforward to add the option and the `SerializationFeature.INDENT_OUTPUT` configuration to the Jackson mapper.

**Comment by cjelger** [comment]
I already have a ready PR for this feature, but I'm waiting for some official approval from my employer to be able to commit it.

**Comment by langecode** [comment]
Resolved with PR #13
