### ISSUE TITLE
implement a skip flag

### ISSUE THREAD

**Issue by sunnymoon** [openapi-tools/swagger-maven-plugin#19]
It would be nice if this plugin had a skip flag that could be used to skip generation, like most maven plugins support.

**Comment by langecode** [comment]
Solved in PR #20

**Comment by sunnymoon** [comment]
Any plans to release this version of the plugin?

**Comment by langecode** [comment]
Release as [2.0.3](https://github.com/openapi-tools/swagger-maven-plugin/releases/tag/v2.0.3)

**Comment by sunnymoon** [comment]
Brilliant.

Many tks
Jp

A sábado, 23/02/2019, 09:24, Thor Anker Kvisgård Lange <
notifications@github.com> escreveu:
