### ISSUE TITLE
byte[] not correctly handled by openapi converter

### ISSUE THREAD

**Issue by andreas-eternach** [openapi-tools/swagger-maven-plugin#22]
I tried to generate an OpenApi-Definition from a java-class.

I run into problems with byte-arrays. Those are generated as openapi-arrays, but the openapi-tools create java-lists for openapi-arrays.

The OpenApi-Generator should instead generate a string with format binary according to the swagger-spec (https://swagger.io/docs/specification/data-models/data-types/, section strings)

Please find the sample code in the attachted [openapi-byte-array.zip](https://github.com/openapi-tools/swagger-maven-plugin/files/2970050/openapi-byte-array.zip)

It contains also a maven-pom-template for configuring the maven-swagger-plugin.

I ran the plugin from command line with

mvn io.swagger.core.v3:swagger-maven-plugin:2.0.7:resolve
The expected openapi-output for a byte[] is:

```json
        "binaryContent" : {
          "type" : "string",
          "format": "byte", 
          "description" : "base64 encoded binary content."
        }
```
This would would work with the openapi-generator-plugin [https://github.com/OpenAPITools/]:
```xml
    <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>3.3.3</version>
        <executions>
          <execution>
            <id>8djh-jom-client</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>${project.basedir}/src/main/openapi/openapi.json</inputSpec>
              <generateDirectory>${project.build.directory}/generated-sources</generateDirectory>
              <generatorName>java</generatorName>
              <generateApiTests>false</generateApiTests>
              <generateModelTests>false</generateModelTests>
              
              <configOptions>
                <sourceFolder>test-rest-client</sourceFolder>
                <apiPackage>test.api</apiPackage>
                <modelPackage>test.model</modelPackage>
                <library>resttemplate</library>
                <dateLibrary>java8</dateLibrary>
              </configOptions>
            </configuration>
          </execution>
        </executions>
      </plugin>
```
do i miss something? Do i need to register a converter ?

**Comment by andreas-eternach** [comment]
also created an issue in the related project, not sure where is the right place, maybe not at all in the openapi-generators but somwhere in the java-annotation-handling ?

https://github.com/swagger-api/swagger-core/issues/3154

**Comment by langecode** [comment]
Hi... Thanks for the report.. I will look into it.. Basically the whole intention of `io.openapitools.swagger:swagger-maven-plugin` was to create a wrapper as thin as possible around the `swagger-core` modules. So I am pretty sure the specification generated comes from Swagger itself. But I will check it out as soon as possible

**Comment by andreas-eternach** [comment]
i did some more analyses and found in the springfox-project an issue with similar description, see https://github.com/springfox/springfox/issues/1605

It also contains a ModelConverter for fixing the issue, i guess i can pass ModelConverters in the configuration-parameters for the sagger-maven-plugin

Local debugging showed that the responsible code is here: io.swagger.jackson.ModelResolver.resolveProperty(JavaType, ModelConverterContext, Annotation[], Iterator<ModelConverter>)

**Comment by andreas-eternach** [comment]
This is the solution:

```
  @ApiModelProperty(dataType = "BYTE")
  public byte[] getByteArrayAsString() {
}
```

**Comment by langecode** [comment]
Thanks for reporting back and closing the issue.

**Comment by tisoft** [comment]
Just for reference, if you want to use the `io.swagger.core.v3:swagger-annotations`, then use this:

```
   @ApiResponse (description = "default response",
                 content = @Content (schema = @Schema (type = "string",
                                                       format = "byte")))

```

**Comment by falk-stefan** [comment]
@tisoft Somehow this does not seem to work for me. My generated client tries to parse the response body as JSON, even though it's just a byte array (see https://stackoverflow.com/questions/64080432/how-to-declare-binary-data-response-content-type-correctly).


![image](https://user-images.githubusercontent.com/58136779/94346336-48826c00-002c-11eb-8795-2e16e4ee6d30.png)

**Comment by p4535992** [comment]
> This is the solution:
> 
> ```
>   @ApiModelProperty(dataType = "BYTE")
>   public byte[] getByteArrayAsString() {
> }
> ```

Sorry how can i use this solution on the maven plugin configuration ? There is some model converter to registered ?
