### ISSUE TITLE
@ApplicationPath seems to be ignored by the plugin

### ISSUE THREAD

**Issue by tosix1988** [openapi-tools/swagger-maven-plugin#23]
The swagger maven plugin does not take the `javax.ws.rs.Application` class and `@ApplicationPath` and its base URI into consideration when it generates the documentation. All paths that are generated by the plugin are missing the base URI provided by the annotation. Documentation generated by swagger JAX-RS resources handle this correctly.

To demonstrate this, I have set up a sample project that uses both the swagger resource and this plugin to create the openapi documentation. I have also attached the outputs they provide (in json format), wherer the difference can be clearly seen.

The reason for the difference is that the `GenerateMojo` instantiates the swagger `Reader` instance, but it does not provide it with the instance of `javax.ws.rs.Application` (possibly annotated with `@ApplicationPath`). As a consequence of this, the `Reader` produces the `OpenApi` instance, but ignores the Application. Luckily, it is possible to work around this limitation by creating custom `ReaderListener` (however, it must be annotated by `@OpenAPIDefinition`, otherwise it is not picked up by the plugin) and set the application class to the provided `Reader` by calling `reader#setApplication(...)`), however, I think that the plugin could somehow support this out of the box. My thoughs:

- an additional parameter could be added to the plugin configuration, where the fully qualified name of the Application class could be specified
- a classpath scanning could be performed to find the class automatically

Do you think this might be useful?

The json documentations for comparison:
[swagger_docs.zip](https://github.com/openapi-tools/swagger-maven-plugin/files/3024079/swagger_docs.zip)

The sample project:
[swagger-maven-plugin-sample-project.zip](https://github.com/openapi-tools/swagger-maven-plugin/files/3024084/swagger-maven-plugin-sample-project.zip)

**Comment by langecode** [comment]
Thanks for reporting. That is a good point. Basically we try to mimic the same behaviour as the servlet for dynamic triggering generation in the swagger jaxrs module. But it makes good sense to look at the path from the `@Application` annotation.

**Comment by tosix1988** [comment]
Hi @langecode , thanks for your quick response. I have been playing with the plugin a bit, and I can submit a pull request with this feature if you are interested.

**Comment by langecode** [comment]
@tosix1988, that would be great. You are welcome to do so, thx.
