### ISSUE TITLE
Add support for OpenAPI v3

### ISSUE THREAD

**Issue by langecode** [openapi-tools/swagger-maven-plugin#3]
Swagger 2.x.x is out with support for OpenAPI specification v3. The Maven plugin should be updated to support this.

**Comment by philsturgeon** [comment]
Is this issue still being worked on? Is this project in general still being worked on? 

It seems like you dropped Spring MVC support from swagger-maven-plugin, is that the case?

**Comment by langecode** [comment]
Yes, this issue is in progress - I expect a release built on Swagger 2.x.x to come out shortly.

With respect to your question about Spring MVC support. The point of this plugin was to base generation on the functionality already present in Swagger doing only a thin wrapper around this. The original swagger-maven-plugin (also mentioned in our acknowledgements) did a lot of re-implementation of endpoint scanning and more but missing out some features from the Swagger scanning. But since this plugin is a wrapper around the Swagger JAX-RS module there is no Spring support as such.
