### ISSUE TITLE
Field ordering not maintained in generated object descriptions

### ISSUE THREAD

**Issue by pisajew** [openapi-tools/swagger-maven-plugin#42]
**Describe the bug**
On subsequent executions on the same codebase the ordering of attributes is random. This leads to incompatible constructor signatures in generated client code.

**To Reproduce**
- create maven project that generates JSON/YAML api descriptions for some Java source
- execute the build several times (keeping the generated yaml/json api descriptions)
- compare generated api descriptions

**Expected behavior**
- API descriptions generated by all the executions are identical

**Additional context**
Randomizing attribute ordering leads to different constructor signatures for object in generated client code. This requires changes to the source code using generated client every time the client is generated based on regenerated API description.

**Comment by langecode** [comment]
Thank for reporting. I am pretty sure this is the behaviour of Swagger, not this Maven plugin. The basic idea was to be a thin wrapper around the Swagger framework.

**Comment by pisajew** [comment]
Agreed, it's either swagger-codegen in general or it's specific swift4 target. Any way this issue doesn't belong here.
