### ISSUE TITLE
Bump swagger-core for enum fix

### ISSUE THREAD

**Issue by jlous** [openapi-tools/swagger-maven-plugin#52]
Would much appreciate if swagger-core could be updatetd to 2.1.3 or later, as it fixes an important regression in how enum values are inspected
(Support for overriding enum values with @JsonProperty or @JsonValue ([#3553](https://github.com/swagger-api/swagger-core/pull/3553)))

**Comment by langecode** [comment]
You should abe able to override plugin dependencies in your pom. But next release (this week) will include a reference to 2.1.4.
