### ISSUE TITLE
parent packeage are not supported

### ISSUE THREAD

**Issue by dvivarelli** [openapi-tools/swagger-maven-plugin#8]
In resourcePackages i have to put every package I use.
For example if the Api class is in com.foo.bar but the response object is in com. foo.foo i can't put just com.foo in the resourcePackages .
Could it be useful change this line of code resourcePackages.contains(cls.getPackage().getName()) in JaxRSScanner to enable parent package

**Comment by langecode** [comment]
You are right the scanning is not recursive as it is. This behaviour should be similar to the behaviour in the Swagger API servlet.

It should not be necessary to list the packages of the model classes - only the endpoint classes - however I guess the plugin could be extended with an option to do recursive scanning. Doing recursive scanning, as you suggest, would be closer to the current working of [JaxrsAnnotationScanner](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/integration/JaxrsAnnotationScanner.java) in Swagger Core.

**Comment by langecode** [comment]
A bit unsure whether this should be a new option or whether we should introduce this as default behaviour. I guess it should be a very special case if this change breaks anything.

**Comment by langecode** [comment]
Solved in #20
