### ISSUE TITLE
V1.0.2 does not find any of my jaxrs classes

### ISSUE THREAD

**Issue by antonaustirol** [openapi-tools/swagger-maven-plugin#9]
V1.0.2 does not work  or maybe does not work with maven 3?
It does not find any of my classes for further processing the jaxrs annotations. 
After I copied  createClassLoader() from GenerateMojo from V2.0.1 over and the related init process the plugin works as expected.
I think there might be still reasons out there to use the Swagger Spec 2.0 for some people so it would be helpful to keep the V1.x alive. And the fix is so small - once the issue is found ;-)

**Comment by langecode** [comment]
True. We recently did this fix on the 2.0 version. There is a workaround by adding the project itself as dependency of the plugin - see [#5](https://github.com/openapi-tools/swagger-maven-plugin/issues/5#issuecomment-433734407). But I agree it might be worth back porting this to version 1.0.

**Comment by langecode** [comment]
Fixed by release [1.0.3](https://github.com/openapi-tools/swagger-maven-plugin/releases/tag/v1.0.3)
